name: Releases

on:
  push:
    branches: ["main"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Set execute permission for build.sh
        run: chmod +x build/build.sh

      - name: Build ZIP archive
        run: bash build/build.sh

      - name: Tag new version
        id: tagger
        uses: phish108/autotag-action@v1.1.64
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          bump: minor
          with-v: true
          release-branch: main

      - name: Create release on Github
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.tagger.outputs.new-tag }}"
          artifacts: build/logfire-aws-lambda.zip